export const MessageTypes = {
    DOWNLOADING: "DOWNLOADING",
    LOADING: "LOADING",
    RESULT: "RESULT",
    RESULT_PARTIAL: "RESULT_PARTIAL",
    INFERENCE_REQUEST: "INFERENCE_REQUEST",
    INFERENCE_DONE: "INFERENCE_DONE",
};

export const LoadingStatus = {
    SUCCESS: "success",
    ERROR: "error",
    LOADING: "loading",
};

export const ModelNames = {
    WHISPER_TINY_EN: "Xenova/whisper-tiny.en",
    WHISPER_TINY: "Xenova/whisper-tiny",
    WHISPER_BASE: "Xemova/whisper-base",
    WHISPER_BASE_EN: "Xenova/whisper-base.en",
    WHISPER_SMALL: "Xenova/whisper-small",
    WHISPER_SMALL_EN: "Xenova/whisper-small.en",
};

export const LANGUAGES = {
    "Acehnese": "ace",
    "Afrikaans": "af",
    "Akan": "ak",
    "Amharic": "am",
    "Armenian": "hy",
    "Assamese": "as",
    "Asturian": "ast",
    "Awadhi": "awa",
    "Ayacucho Quechua": "quy",
    "Balinese": "ban",
    "Bambara": "bam",
    "Bashkir": "ba",
    "Basque": "eu",
    "Belarusian": "be",
    "Bemba": "bem",
    "Bengali": "bn",
    "Bhojpuri": "bho",
    "Bosnian": "bs",
    "Buginese": "bug",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Central Atlas Tamazight": "tzm",
    "Central Aymara": "ayr",
    "Central Kanuri": "knc",  // Both scripts are valid, just use 'knc'
    "Central Kurdish": "ckb",
    "Chhattisgarhi": "hne",
    "Chinese (Simplified)": "zh",
    "Chinese (Traditional)": "zh",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dari": "prs",
    "Dutch": "nl",
    "Dyula": "dyu",
    "Dzongkha": "dz",
    "Eastern Panjabi": "pa",
    "English": "en",
    "Esperanto": "eo",
    "Estonian": "et",
    "Ewe": "ee",
    "Faroese": "fo",
    "Fijian": "fj",
    "Finnish": "fi",
    "Fon": "fon",
    "French": "fr",
    "Friulian": "fur",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Guarani": "gn",
    "Gujarati": "gu",
    "Haitian Creole": "ht",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Ilocano": "ilo",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Korean": "ko",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kikongo": "kg",
    "Kikuyu": "ki",
    "Kinyarwanda": "rw",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Macedonian": "mk",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Maori": "mi",
    "Marathi": "mr",
    "Nepali": "ne",
    "Norwegian": "no",
    "Odia": "or",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Sanskrit": "sa",
    "Serbian": "sr",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Spanish": "es",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tamil": "ta",
    "Telugu": "te",
    "Thai": "th",
    "Tigrinya": "ti",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Vietnamese": "vi",
    "Yoruba": "yo",
    "Zulu": "zu"
};
